from tkinter import *
def click(event):
    global scvalue
    text=event.widget.cget("text")
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            try:
                value = eval(screen.get())

            except Exception as e:
                print(e)
                value = "Error"

        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.udpate()


root = Tk()
root.geometry("300x550")
root.title("CALCULATOR")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font="Gadugi 14 bold",bg="white")
screen.pack(fill=X,pady=10,padx=2,ipadx=10)
f=Frame(root,bg="grey")
b=Button(f,text="9",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="8",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="7",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f.pack(fill=X)
f=Frame(root,bg="grey")
b=Button(f,text="4",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="5",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="6",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f.pack(fill=X)
f=Frame(root,bg="grey")
b=Button(f,text="3",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="2",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="1",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f.pack(fill=X)
f=Frame(root,bg="grey")
b=Button(f,text="0",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="-",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="*",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f.pack(fill=X)
f=Frame(root,bg="grey")
b=Button(f,text="/",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="%",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="C",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f.pack(fill=X)
f=Frame(root,bg="grey")
b=Button(f,text=".",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="=",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
b=Button(f,text="00",font="lucida",width=9,height=3)
b.pack(side=LEFT)
b.bind("<Button-1>",click)
f.pack(fill=X)
root.mainloop()